### ISSUE TITLE
集成JXCategoryView的页面会有多个导航栏

### ISSUE THREAD

**Issue by anomot** [zongmumask/YRNavigationBarPure#4]

**Comment by zongmumask** [comment]
方便加个微信不 问问具体问题 截图

**Comment by anomot** [comment]
可以啊。
wzt618i 
加这个微信号吧


2020-09-08
| |
王子通
|
|
haomilong@163.com
|
签名由网易邮箱大师定制
在2020年09月7日 09:04，Daniel_Hu<notifications@github.com> 写道：

方便加个微信不 问问具体问题 截图

**Comment by zongmumask** [comment]
v0.0.3已修复
